databases:
  - name: monndb
    databaseName: monndb
    user: monn
    plan: free # Ensure the database uses the free plan

services:
  # Redis for cache and background jobs
  - type: redis
    name: sidekiq-redis
    ipAllowList: [] # Only allow internal connections
    plan: free # Specify the free plan for Redis
    maxmemoryPolicy: noeviction

  # Background jobs worker
  - type: worker
    name: sidekiq-worker
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -C config/sidekiq.yml
    envVars:
      # Give access to the database
      - key: DATABASE_URL
        fromDatabase:
          name: monndb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL # This must match the name of the environment variable used in production.rb
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString

  # Main app
  - type: web
    name: monn
    env: ruby
    plan: free # Use the free plan for the web service
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: monndb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL # This must match the name of the environment variable used in production.rb
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
